language: node_js
node_js:
  - "0.12"
sudo: false
install:
  - npm install
  - npm install $TYPESCRIPT
env:
  - TYPESCRIPT=typescript@1.6.2
  - TYPESCRIPT=typescript@1.7.5
  - TYPESCRIPT=typescript@1.8.0
  - TYPESCRIPT=typescript@next